format = """
$time\
$memory_usage\
$python
$directory\
$git_branch\
${custom.git_worktree}\
$git_status\
"""

[directory]
format = "[ $path > ](fg:#7daea3)"

[git_branch]
format = "[ $branch](fg:#e78a4e)"

[git_status]
format = "[\\($all_status\\) > ](fg:#e78a4e)"

[time]
format = "[【$time】](fg:#ea6962)"
disabled = false

[memory_usage]
format = "[Ram \\[$ram_pct\\] ](fg:#a9b665)"
disabled = false
threshold = 0

[python]
format = "[$virtualenv](fg:#d8a657)"

[custom.git_worktree]
command = "basename $(git rev-parse --show-toplevel)"
when = """t=$(git rev-parse --show-toplevel 2>/dev/null) && c=$(cd "$t" && realpath "$(git rev-parse --git-common-dir)") && [ "$t" != "${c%/.git}" ]"""
format = "[@$output](fg:#d3869b) "
shell = ["bash", "--nologin"]
